# Cloudflare Pages Configuration
name = "dharmaradio"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./build/client"

[triggers]
crons=["0 */6 * * *"] # Run every 6 hours 

[[d1_databases]]
binding="DB" # available in your Worker as env.DB
database_name="dharmaradio"
database_id="c3eadb2d-f09e-4cf5-a956-ce883afd1614"
migrations_dir="./app/db/migrations"